# Generated by Django 4.2.7 on 2025-03-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_deliveryboy_deliveryassignment_deliveryboyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplieractivity',
            name='activity_type',
            field=models.CharField(choices=[('restock_request', 'Restock Request'), ('restock_completed', 'Restock Completed'), ('restock_rejected', 'Restock Rejected'), ('stock_update', 'Stock Update'), ('approval_status', 'Approval Status Change')], default='stock_update', max_length=20),
            preserve_default=False,
        ),
    ]
