# Generated by Django 4.2.7 on 2025-03-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_deliverychat_is_system_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True),
        ),
    ]
