# Generated by Django 4.2.7 on 2025-03-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_deliveryassignment_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryboy',
            options={},
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='deliveryboy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='id_proof',
            field=models.FileField(blank=True, upload_to='delivery_boy_docs/'),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='deliveryboy',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
    ]
