# Generated by Django 4.2.7 on 2025-03-22 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_restockrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restockrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_requests', to='store.product'),
        ),
    ]
