# Generated by Django 4.2.7 on 2025-03-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_restockrequest_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
